service: admin-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
    AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  run:
    handler: handler.handle
    events:
      - http:
          path: /{proxy+}
          method: any
